#!/bin/bash
#Proyecto de Egreso
#Participantes:
#	Tiago Silva
#	Nahuel Matrinez
#	Santiago Serena
#	Marco Bottini
function menu(){
	echo "MENU PRINCIPAL"
	echo "1)Agregar usuario"
	echo "2)Agregar grupo"
	echo "3)Eliminar usuario"
	echo "4)Respaldar"
	echo "5)Salir"
	echo
	echo -n "Elije una opcion: "
	read opcion
}

function realizarAccion(){
	echo ""
	case $opcion in
	1)
		echo "Nombre de usuario a agregar:"
		read user
		comando=$(grep -w $user /etc/passwd | wc -l)
		if [ $comando -eq 0 ]
		then
			sudo adduser $user
			echo "Usuario creado correctamente."
		else
			echo "No puede crearse, ya existe dicho usuario."
		fi
	;;
	2)
		echo "Nombre de grupo a agregar:"
		read group
		comandogrupo=$(grep -w $group /etc/group | wc -l)
		if [ $comandogrupo -eq 0 ]
		then
			sudo groupadd $group
			echo "Grupo creado correctamente."
		else
			echo "No puede crearse, ya existe dicho grupo."
		fi
	;;
	3)
		echo "Nombre de usuario a eliminar:"
		read user
		comando=$(grep -w $user /etc/passwd | wc -l)
		if [ $comando -ne 0 ]
		then
			sudo userdel -r $user
			echo "Usuario eliminado correctamente."
		else
			echo "No puede eliminarse, no existe dicho usuario."
		fi
	;;
	4)
		echo "Esta opcion se encuentra en desarrollo"
	;;
	5)
		exit
	;;
	*)
		echo "Debe seleccionar un opcion correcta"
	;;
	esac
echo ""
}
num=0
while [ $num -ne '5' ]
do
	menu
	realizarAccion
done
